apiVersion: apps/v1
kind: Deployment
metadata:
 name: resultapp-deployment
 labels:
  app: demo-votingapp
spec:
  replicas: 1
  selector:
   matchLabels:
    name: resultapp-pod
    app: demo-votingapp
  template:
    metadata:
      name: resultapp-pod
      labels:
        name: resultapp-pod
        app: demo-votingapp
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
          - containerPort: 80